---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lw.
--- DateTime: 2021/12/22 10:29
---读取当前已购买数量，判断如果小于库存总数10000 则递增已购买数量 返回true 否则返回false
---
local localKey = KEYS[1]
local result_1 = redis.call('GET',localKey)
if tonumber(result_1) < 10
then
    redis.call('INCR',localKey)
    return true
else
    return false
end 